---
title: 'RMarkdown:  In Class Assignment'
author: "Justin Perez"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
  ## Everything above this is R code that we need to make the file run! We'll discuss it next class.
```


Reminder: We learned how to do these things in class today, but there is a "Markdown Help" page available in RStudio (and lots of help if you google). 


# In-class Activity, Markdown

**Do not skip reading this line** Create a new section at the end of this file with the title "Your work here", and beneath it, do the following 3 things. To turn this in, make sure you've committed and pushed, and turn in the link to this repository to the assignment on Blackboard.  

1. Make a subsection called Wise words. Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

2. Make a subsection called My semester. Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

- A _subsubheading_ with the name of the artist or author;    
- An example of their writing or lyrics (formatted in a *block of text*);   
- A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     


Note that you can click "Knit" as you go along to see what the final results are going to look like. The knitting will produce an html file, which you will also need to stage/commit/push once it exists! 

**Once you're done, remember to commit the changes and push the repo back to your assignment on GitHub!**

# Your work here

## Wise words


>Don't take yourself too seriously.

[More info...](https://www.thegoodtrade.com/features/taking-yourself-too-seriously/)


## My semester

|Course number|Course title|Instructor name|
|:------------|:-----------|:--------------|
|2401|Data Science 1|Shoemaker|

## I recommend

### Nathaniel Hawthorne

>AFTER the kings of Great Britain had assumed the right of appointing the colonial governors, the >measures of the latter seldom met with the ready and generous approbation which had been paid to >those of their predecessors, under the original charters.


- Twice-Told Tales (1837)
- Legends of the Province House (1838–1839)
- Grandfather's Chair (1840)
- Mosses from an Old Manse (1846)
- A Wonder-Book for Girls and Boys (1851)
- The Snow-Image, and Other Twice-Told Tales (1852)
- Tanglewood Tales (1853)
- The Dolliver Romance and Other Pieces (1876)
- The Great Stone Face and Other Tales of the White Mountains (1889)



 
